const products = [
  {
    id: "1",
    name: "Product 1",
    category: "Category 1",
    price: 10.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "2",
    name: "Product 2",
    category: "Category 2",
    price: 20.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "3",
    name: "Product 3",
    category: "Category 1",
    price: 15.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    id: "4",
    name: "Product 4",
    category: "Category 4",
    price: 10.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "5",
    name: "Product 5",
    category: "Category 5",
    price: 20.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "6",
    name: "Product 6",
    category: "Category 6",
    price: 15.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    id: "7",
    name: "Product 7",
    category: "Category 7",
    price: 10.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "8",
    name: "Product 8",
    category: "Category 8",
    price: 20.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "9",
    name: "Product 9",
    category: "Category 9",
    price: 15.99,
    imageUrl: "https://via.placeholder.com/150",
    isNewArrival: true,
    isBestSeller: true,
  },
];

export default products;
