const orders = [
  // Pending orders
  {
    id: "1",
    status: "pending",
    date: "2024-07-01",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "123-456-7890",
    street: "123 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: "12345",
    specialNote: "Leave at the front door.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 1", quantity: 2, subPrice: 20.99 },
      { name: "Product 2", quantity: 1, subPrice: 10.99 },
    ],
    deliveryFee: 5.99,
    subTotal: 41.97,
    discount: 5.0,
    total: 36.97,
  },
  {
    id: "2",
    status: "pending",
    date: "2024-07-10",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "321-654-0987",
    street: "456 Elm St",
    city: "Othertown",
    state: "TX",
    zipCode: "67890",
    specialNote: "Ring the bell.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 3", quantity: 1, subPrice: 30.99 },
      { name: "Product 4", quantity: 2, subPrice: 15.49 },
    ],
    deliveryFee: 6.99,
    subTotal: 62.97,
    discount: 10.0,
    total: 59.97,
  },

  // Delivered orders
  {
    id: "3",
    status: "delivered",
    date: "2024-07-12",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    phoneNumber: "456-789-0123",
    street: "789 Pine St",
    city: "Sometown",
    state: "FL",
    zipCode: "11223",
    specialNote: "Deliver before 5 PM.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 5", quantity: 1, subPrice: 45.99 },
      { name: "Product 6", quantity: 3, subPrice: 25.99 },
    ],
    deliveryFee: 7.99,
    subTotal: 178.96,
    discount: 15.0,
    total: 171.96,
  },
  {
    id: "4",
    status: "delivered",
    date: "2024-07-20",
    firstName: "Bob",
    lastName: "Brown",
    email: "bob.brown@example.com",
    phoneNumber: "789-012-3456",
    street: "1010 Oak St",
    city: "Newtown",
    state: "NY",
    zipCode: "54321",
    specialNote: "Leave in the garage.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 7", quantity: 4, subPrice: 20.99 },
      { name: "Product 8", quantity: 2, subPrice: 40.99 },
    ],
    deliveryFee: 8.99,
    subTotal: 163.92,
    discount: 20.0,
    total: 152.92,
  },

  // More orders for better coverage
  {
    id: "5",
    status: "delivered",
    date: "2024-06-30",
    firstName: "Charlie",
    lastName: "Davis",
    email: "charlie.davis@example.com",
    phoneNumber: "234-567-8901",
    street: "2020 Maple St",
    city: "Village",
    state: "OH",
    zipCode: "67891",
    specialNote: "Leave with neighbor.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 9", quantity: 2, subPrice: 60.99 },
      { name: "Product 10", quantity: 1, subPrice: 80.99 },
    ],
    deliveryFee: 9.99,
    subTotal: 202.97,
    discount: 25.0,
    total: 177.97,
  },
  {
    id: "6",
    status: "pending",
    date: "2024-07-05",
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@example.com",
    phoneNumber: "567-890-1234",
    street: "3030 Birch St",
    city: "Smalltown",
    state: "MI",
    zipCode: "34567",
    specialNote: "Please call on arrival.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 11", quantity: 3, subPrice: 35.99 },
      { name: "Product 12", quantity: 2, subPrice: 22.99 },
    ],
    deliveryFee: 7.49,
    subTotal: 183.94,
    discount: 10.0,
    total: 173.94,
  },
  {
    id: "7",
    status: "delivered",
    date: "2024-06-25",
    firstName: "Oliver",
    lastName: "Martinez",
    email: "oliver.martinez@example.com",
    phoneNumber: "678-901-2345",
    street: "4040 Cedar St",
    city: "Bigcity",
    state: "WA",
    zipCode: "78912",
    specialNote: "Deliver to the office.",
    picture: "https://via.placeholder.com/150",
    products: [
      { name: "Product 13", quantity: 5, subPrice: 19.99 },
      { name: "Product 14", quantity: 4, subPrice: 29.99 },
    ],
    deliveryFee: 6.49,
    subTotal: 179.92,
    discount: 15.0,
    total: 164.92,
  },
  // Add more orders as needed for better test coverage
];

export default orders;
